{% set name = "flower" %}
{% set version = "0.9.1" %}
{% set md5 = "5d191dae0db989b97d9d000133ead843" %}
{% set build = 0 %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    md5: {{ md5 }}

build:
    number: {{ build }}
    script: python setup.py install --single-version-externally-managed --record=record.txt
    entry_points:
        - flower = flower.__main__:main

requirements:
    build:
        - python
        - setuptools
        - celery >=2.5.0
        - tornado >=4.0.0
        - babel
        - pytz
        - futures
    run:
        - python
        - setuptools
        - celery >=2.5.0
        - tornado >=4.0.0
        - babel
        - pytz
        - futures

test:
    imports:
        - flower
        - flower.api
        - flower.utils
        - flower.utils.backports
        - flower.views
    commands:
        - flower --help

about:
    home: https://github.com/mher/flower
    license: BSD License
    summary: Celery Flower

extra:
    recipe-maintainers:
        - kwilcox
