{% set name = "flower" %}
{% set version = "0.9.5" %}
{% set sha256 = "56916d1d2892e25453d6023437427fc04706a1308e0bd4822321da34e1643f9c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
    number: 0
    noarch: python
    script: {{ PYTHON }} -m pip install --no-deps -vv .
    entry_points:
        - flower = flower.__main__:main

requirements:
  host:
    - python >=3.7
    - pip

  run:
    - python >=3.7
    - setuptools
    - celery >=4.3.0
    - tornado >=5.0.0,<7.0.0
    - humanize >=0.5.1
    - babel >=1.0
    - pytz

test:
  imports:
    - flower
    - flower.api
    - flower.utils
    - flower.views

  commands:
    - flower --help
    
  requires:
    - mock
    
about:
    home: https://github.com/mher/flower
    license: BSD 3-Clause
    summary: Celery Flower
    license_file: LICENSE

extra:
    recipe-maintainers:
        - kwilcox
        - ukaratay
        - thebestnom
