travis:
  secure:
    BINSTAR_TOKEN: x0PHcDa/f1gzQ0jxAVh+Vx38fN3S6Kb+u4fQzGKPfco+sCMulLx0czXBj8/uQBGhlKsHC+EguK4/EgWBZkDn81gE/Xr6VVX5ogwT+2U0aQ/4Tg84gUTSAU3bPjDEJ6h4xg7rnppaG5nuzwLkiBOoMQOK4+npxyr2Wp/+G7XIt7h1Gy0r4UtRSBMafZUZTs0w9cFweRCR/ysW++BCEwLuYBeLjJxA6dmgYIGNOTCd694DnjY8+hAQJMH3g8IC6iCPIHjEAMPS1XEsHVkY3Q2l0F1BGAR0kpb23tmeESuURKofQvbCzoZ8JXif9khj3QP6P86rpTvNxQsOXApq694B+21MIOZqUY1OZqgjQWA3bRbrsTGi+g5uSxuDIr18h9yh7My5zq1yDYTQqsWfivWH4YzHndwUTiATwbjqkkvQRlSsjmEBVzmrq5R8xlZNd9+EDZGQIISuUjkmDfMK3HUFYB/DuS1hGvNvQ14yF7TEc/6dyhzW2UIZWQnTpI7jGUNpRTy5kMyLQvAWSTm0OGqfDiPE+y/FhpVvcPwkBm4FieAd4yBb1Trgj+AZzAOJWledwPXaUVmNh3Jq8iYj3Nj9uoELII93hMtdNnTzfc537NU8M+FPv+8FFCPNgebDiZbIj18hD/UjRUPYqP6d/wuLQvPn/GhHH0x3eBeesCaV4RY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
