travis:
  secure:
    BINSTAR_TOKEN: kgustHXtNy0PmtJ19CxgO2YmfnFtqvQXnhN/2dA3nvLmqjga2mvSaijuH6tQhfLHN55g88i8ur4tEfadetIzaC3FRCIXa7KjOvGU0ZdXNOo2cU/BcmUXvs3W6RnP67HKZY5R1+cFktOPom1wWYaAA6ZEwlW7eYgJijMBAKCtXwZWVuNuM3Q/YjSXEic1fj5LU2uuNAw/GD17gw/fN9gpTqYwCNKIlGsIHrMf6g24zmtze7cM/WWo6/MVQZpxcAiDNXWMMmnhrHkt22/gc/YkgdtI551sQhdm02StKH+BR7TBecMvKo1xwCMUuV7aNccC9dwOgXr/d+GkVYOKerlH5EtohLIUTBLvbjwKEhTBARhCc54wVVz87tEXmdxRglNl9EbTwVnf3z/aANlCAzhNVjcRf4w0/rntFgcNPNJ0rPTFUPw2IEmjeRtghZIlFFkVIoisV3/Ce45dmWuGyBHx2bucE3+xUYV87M8nM8CaFDEiAmpYidrHLLokMlC3MFqkqaOG7Mt6z5HAbLNdPVYuBBDhE0nYipvTQKjWR+IAb/xdXS059JYiKkeaVvjlkzszVrmatARhZsE1u1tA5wp6PWmgnJMhdInT9jqheoTBLh+reXVXFHrsoPPQ881uSzrb8OyiC7qptUB2Iqcs4pkwDZRR+BIpQS2gCVdiJFyqJVY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
