travis:
  secure:
    BINSTAR_TOKEN: 2aqZIGgG7qZdGlWPCXYwe4tfdjC4t+N53IIJOVjcf0iJgsO1eV48lD4cjn2vV+mCslRt/CYMSS1PmEsAKL0fXaIz0KON7pB82Kq2RihOCBRvowmgX176H7ypNkbHv7OJ5MtaGXzsPBfm96Mv2KGcPjzg4q9kIk5zucyXff2kKKr34EW5V4Q8ZEgQ/uTHeHSYywzs4fhJSE7Cs0bIvIsDDQVPC6dCJecmIuGmwrzXbry/Bnm09gg7O2WQ9H1DY9zhaL+sx+Cri8hO0NP0AgiQVtHKHpdk28IsWm59OsZlQB4USX3o/1nW7hzl+knbeuXZ9xf0Dh7xkhrnpsAMuLJMoOQ9AcSSBBnDB+hXb4hFk40NX2kxJ2ro0VRXbR9a5nvYZnl/EqDRlHlFcal1aAj9gR6P/cC2plXqYpXROqsTo/UEspG0ZK1AM5Jk5ErWEl29dIrMOWuCZ5FrmCLZvtPQWnXPvwZFluQb06YnasS0qpPOKuvWVZwMo9Z4tWhg7esAcrC2vnYf/8Lfr9lUr3iLgjoUNQCK4VGC0KgSN5SeVrcdg72nSS/9eu5KDuN03vgWSc3xyUokLDSQUCu9/xIi03LI7dqpoGqfHd+gLC2+SVC+xcX54DeuY5iTgCbnjZhR7VHrggEsHOH3Lnzmqwth+zbM9Kmh1Xu78HUx0i7NiKg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
